// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC942r7ySKfH-NknMiM-94eD_ZZHhvReq8',
    appId: '1:22018595481:web:4c537eed444cc99b0ef608',
    messagingSenderId: '22018595481',
    projectId: 'thinxi2025',
    authDomain: 'thinxi2025.firebaseapp.com',
    storageBucket: 'thinxi2025.firebasestorage.app',
    measurementId: 'G-Q5T1HVF055',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKFh4j_7qoLBZ_sDUWgXOSjkPf4ZZSkMU',
    appId: '1:22018595481:android:89e643a73618b6370ef608',
    messagingSenderId: '22018595481',
    projectId: 'thinxi2025',
    storageBucket: 'thinxi2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACHYEvixfcwguMdjUi7PjSu26UD83Q4Yo',
    appId: '1:22018595481:ios:f1bb88d747a9e6850ef608',
    messagingSenderId: '22018595481',
    projectId: 'thinxi2025',
    storageBucket: 'thinxi2025.firebasestorage.app',
    iosBundleId: 'com.example.thinxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACHYEvixfcwguMdjUi7PjSu26UD83Q4Yo',
    appId: '1:22018595481:ios:f1bb88d747a9e6850ef608',
    messagingSenderId: '22018595481',
    projectId: 'thinxi2025',
    storageBucket: 'thinxi2025.firebasestorage.app',
    iosBundleId: 'com.example.thinxi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC942r7ySKfH-NknMiM-94eD_ZZHhvReq8',
    appId: '1:22018595481:web:8bdda854278c4fd60ef608',
    messagingSenderId: '22018595481',
    projectId: 'thinxi2025',
    authDomain: 'thinxi2025.firebaseapp.com',
    storageBucket: 'thinxi2025.firebasestorage.app',
    measurementId: 'G-7GRY4F7SDM',
  );

}